### ISSUE TITLE
Add a field for the date and time in the Drop model

### ISSUE THREAD

**Issue by tomasg88** [tomasg88/mirage-gallery#33]
## Description
We need to add a Release Date and Time to the drop model. It must be shown in the drop details, under the default tab called About the Project.

It is enough with showing the date in its original value and timezone next to it. However, it would be better if we can show it in the local time of the user instead

### Tasks

- [ ] Add field to Sanity.
- [ ] Show value in the website
- [ ] Test and review with different timezones
