### ISSUE TITLE
Show Presale or Public sale

### ISSUE THREAD

**Issue by tomasg88** [tomasg88/mirage-gallery#34]
## Description
The smart contract for minting allows for Presale and Public sale. We have to send different fields depending on the type of sale.

### Tasks
This minting form is shown at Curated -> click on any drop -> click on the Mint tab

- [x] Fetch information from contract 
- [x] Determine if it is Public sale or Pre sale
- [x] Show the amount available depending on the case
- [x] Adapt minting form depending the type of sale
