### ISSUE TITLE
"Become a curated artist" form

### ISSUE THREAD

**Issue by tomasg88** [tomasg88/mirage-gallery#35]
## Description
In the home page there is a form that allows users to submit some information for becoming a curated artist in Mirage Gallery. This information needs to be stored so that the Mirage Gallery team can review the submission. For now, there has been between 10 and 20 submissions per month (150 submissions from Jan 2022 until today, March 1st, 2023). 

In sakes of not using yet another platform just for this, we will research the possibility of reusing Sanity to store this content. Given that we know the data model, we can add an automatic field for the status that gets filled on creation.

### Tasks

- [ ] Investigate Sanity to write from the website
- [ ] If so, integrate and test writing from the web
- [ ] Add new `status` field in the model with 2 possible values: Pending and Reviewed. It should get filled with the default value Pending on creation.
- [ ] Check if a "Comments after review" box is desired to write down thoughts on the next steps for that artist

**Comment by tomasg88** [comment]
Sanity docs for creating documents programmatically: https://www.sanity.io/docs/js-client#creating-documents
