### ISSUE TITLE
Add field validations in CMS

### ISSUE THREAD

**Issue by tomasg88** [tomasg88/mirage-gallery#42]
## Description
We have to add some validations to the Sanity models to prevent bugs or weird behaviors in the website due to lack of information. 

### Tasks

- [x] Add field validations in `drops` schema
- [x] Add field validations in `alejandro-and-taylor` schema.
- [x] For _optional fields_, check in website that these have values before using to avoid errors
- [x] Field `openSeaUrl` from A & T schema should be moved to Drops schema

**Comment by tomasg88** [comment]
Validations in PR description are ok.
Only change is that `openSeaUrl` should be placed in **Drops** schema instead of **A & T** schema.

**Comment by tomasg88** [comment]
@augustfr updating this issue as per our convo yesterday
