### ISSUE TITLE
"Become a Curated Artist" form - v2

### ISSUE THREAD

**Issue by tomasg88** [tomasg88/mirage-gallery#48]
# Description
Now that form is storing data in Sanity, we need to include these features to the whole flow to give the user a better UX

## Tasks 

- [ ] export form fields to single components (mostly `<input />`)
- [ ] Install package [react-hook-form](https://react-hook-form.com/)
- [ ] Add form field basic validations (required fields, email format) and error messages
- [ ] Show form status accordingly (loading, if there were any errors, or success message)
- [ ] Send email copy to user as confirmation - nice to have
