### ISSUE TITLE
Replace hexadecimal values in `className`

### ISSUE THREAD

**Issue by tomasg88** [tomasg88/mirage-gallery#50]
# Description
We need to move all hexadecimal values in `classNames` around the code. If all _special colors_ are configured in just one place it would improve code readability across all files and setup in just one file. Below are some hexadecimal that repeat around several files:
* `#920d3d` - dark-red - 18 results 11 files
* `#074f65` - turquoise :thinking: - 7 results 4 files
* `#431281` - dark purple :thinking: - 9 results 5 files
* `#808080` - gray 1 - 8 results 5 files
* `#fdf7f7` - gray 2 - 1 result 1 file
* `#C02828` - another red - 3 results 2 files
* `#f5f5f5` - gray 3 - 4 results 2 files
* `#213bc7` - another blue - 5 results 2 files (note: 4 results are in a stroke attribute of an .svg)
* `#1129aa` - another blue - 6 results 4 files

**Tailwind docs** 
* https://tailwindcss.com/docs/theme#colors
* https://tailwindcss.com/docs/colors

## Tasks

- [x] update tailwind.config.js with these hexa values 
- [x] replace hexa with tailwind classes
- [x] test and check that colors are the same

**Comment by santuan** [comment]
Done in branch 
https://github.com/tomasg88/mirage-gallery/tree/feat/tailwind-config-colors
