### ISSUE TITLE
Add new field and individual pages for Alejandro & Taylor

### ISSUE THREAD

**Issue by tomasg88** [tomasg88/mirage-gallery#62]
# Description
Create a new field in Alejandro & Taylor schema to identify which collections belong to Alejandro and which ones to Taylor.

### Tasks

- [ ] Add new field in Sanity as a radio button allowing to choose between one or the other
- [ ] Create 2 hardcoded pages with names `alejandro.tsx` (already exists) and `taylor.tsx` (new one)
- [ ] Create one query accepting the either alejandro or taylor as params
